// The 166 tracked funds, in case-insensitive alphabetical order by name — the
// dashboard, the timeline and the download list them in this order. Slugs
// match the scraper module filenames in
// src/server/scrapers/; display names come from scrapa/all.json (with the
// "General Catalys" typo fixed and Octopus Ventures added). url is the fund's
// public portfolio page (for the API-based scrapers it's the human-facing
// equivalent of the scraped endpoint).
export interface FundInfo {
	slug: string;
	name: string;
	url: string;
}

export const FUNDS: FundInfo[] = [
	{ slug: '01a', name: '01A', url: 'https://01a.com/portfolio' },
	{ slug: '10d', name: '10D', url: 'https://www.10d.vc/portfolio/' },
	{ slug: '2150', name: '2150', url: 'https://www.2150.vc/investments' },
	{ slug: '3vc', name: '3VC', url: 'https://three.vc/portfolio/' },
	{ slug: '500', name: '500 Global', url: 'https://500.co/portfolio' },
	{ slug: '7percent', name: '7percent', url: 'https://www.7pc.vc/portfolio' },
	{ slug: '83north', name: '83North', url: 'https://www.83north.com/companies/' },
	{ slug: 'acapital', name: 'A Capital', url: 'https://acapital.com/portfolio' },
	{ slug: 'accel', name: 'Accel', url: 'https://www.accel.com/companies' },
	{ slug: 'advent', name: 'Advent International', url: 'https://www.adventinternational.com/investments/' },
	{
		slug: 'airbusventures',
		name: 'Airbus Ventures',
		url: 'https://www.airbusventures.vc/portfolio'
	},
	{ slug: 'aisling', name: 'Aisling Capital', url: 'https://www.aislingcapital.com/portfolio' },
	{
		slug: 'alchemist',
		name: 'Alchemist Accelerator',
		url: 'https://www.alchemistaccelerator.com/portfolio'
	},
	{ slug: 'aleph', name: 'Aleph', url: 'https://www.aleph.vc/companies' },
	{ slug: 'alumni', name: 'Alumni Ventures', url: 'https://www.av.vc/portfolio' },
	{ slug: 'a16z', name: 'Andreessen Horowitz', url: 'https://a16z.com/portfolio/' },
	{ slug: 'antler', name: 'Antler', url: 'https://www.antler.co/portfolio' },
	{ slug: 'apex', name: 'Apex Ventures', url: 'https://www.apex.ventures/portfolio' },
	{ slug: 'archventure', name: 'ARCH Venture Partners', url: 'https://archventure.com/portfolio/' },
	{ slug: 'atlas', name: 'Atlas Venture', url: 'https://atlasventure.com/portfolio/' },
	{ slug: 'av8', name: 'AV8', url: 'https://av8.vc/our-portfolio/' },
	{ slug: 'avp', name: 'AVP', url: 'https://avpcap.com/companies/' },
	{ slug: 'aws', name: 'aws', url: 'https://www.gruendungsfonds.at/portfolio' },
	{ slug: 'b2venture', name: 'b2venture', url: 'https://www.b2venture.vc/portfolio' },
	{ slug: 'baincapital', name: 'Bain Capital Ventures', url: 'https://baincapitalventures.com/portfolio/' },
	{ slug: 'balderton', name: 'Balderton', url: 'https://www.balderton.com/companies/' },
	{ slug: 'base10', name: 'Base10', url: 'https://base10.vc/' },
	{ slug: 'battery', name: 'Battery Ventures', url: 'https://www.battery.com/company/' },
	{ slug: 'behold', name: 'Behold Ventures', url: 'https://behold.vc/portfolio' },
	{ slug: 'bessemer', name: 'Bessemer Venture Partners', url: 'https://www.bvp.com/companies' },
	{ slug: 'bluventures', name: 'Blu Ventures', url: 'https://www.bluventureinvestors.com/portfolio' },
	{ slug: 'blume', name: 'Blume', url: 'https://blume.vc/startups' },
	{ slug: 'boxgroup', name: 'BoxGroup', url: 'https://www.boxgroup.com/portfolio' },
	{ slug: 'breakthrough', name: 'Breakthrough Energy', url: 'https://www.breakthroughenergy.org/portfolio/index.html' },
	{ slug: 'broocknell', name: 'Broocknell Ventures', url: 'https://broocknell.com/all-projects/' },
	{ slug: 'calmstorm', name: 'Calm/Storm', url: 'https://www.calmstorm.vc/portfolio' },
	{ slug: 'canapi', name: 'Canapi', url: 'https://www.canapi.com/portfolio' },
	{ slug: 'cherry', name: 'Cherry Ventures', url: 'https://www.cherry.vc/founders' },
	{ slug: 'congruent', name: 'Congruent Ventures', url: 'https://www.congruentvc.com/portfolio' },
	{ slug: 'craft', name: 'Craft Ventures', url: 'https://www.craftventures.com/portfolio' },
	{ slug: 'creandum', name: 'Creandum', url: 'https://creandum.com/commitments/' },
	{ slug: 'credo', name: 'Credo', url: 'https://www.credoventures.com/portfolio' },
	{ slug: 'cyberstarts', name: 'Cyberstarts', url: 'https://www.cyberstarts.com/portfolio' },
	{ slug: 'dcvc', name: 'DCVC', url: 'https://www.dcvc.com/companies' },
	{ slug: 'draper', name: 'Draper Associates', url: 'https://www.draper.vc/portfolio' },
	{ slug: 'earlybird', name: 'Earlybird', url: 'https://earlybird.com/companies' },
	{ slug: 'eclipse', name: 'Eclipse Ventures', url: 'https://eclipse.capital/portfolio/' },
	{ slug: 'entree', name: 'Entrée Capital', url: 'https://entreecap.com/companies' },
	{ slug: 'ef', name: 'Entrepreneurs First', url: 'https://www.joinef.com/portfolio/' },
	{ slug: 'episode1', name: 'Episode 1', url: 'https://www.episode1.com/portfolio' },
	{ slug: 'eqt', name: 'EQT Group', url: 'https://eqtgroup.com/about/current-portfolio' },
	{ slug: 'f2', name: 'F2 Venture Capital', url: 'https://www.f2vc.com/companies' },
	{ slug: 'felicis', name: 'Felicis', url: 'https://www.felicis.com/companies' },
	{ slug: 'filrouge', name: 'Fil Rouge Capital', url: 'https://www.filrougecapital.com/portfolio' },
	{ slug: 'firstround', name: 'First Round', url: 'https://www.firstround.com/companies' },
	{ slug: 'flagship', name: 'Flagship Pioneering', url: 'https://www.flagshippioneering.com/companies' },
	{ slug: 'fly', name: 'Fly', url: 'https://fly.vc/portfolio' },
	{ slug: 'flybridge', name: 'Flybridge', url: 'https://www.flybridge.com/portfolio' },
	{ slug: 'foundersfund', name: 'Founders Fund', url: 'https://foundersfund.com/portfolio/' },
	{ slug: 'g2', name: 'G2', url: 'https://g2vp.com/portfolio/' },
	{ slug: 'generalatlantic', name: 'General Atlantic', url: 'https://www.generalatlantic.com/investments/' },
	{ slug: 'generalcatalyst', name: 'General Catalyst', url: 'https://www.generalcatalyst.com/portfolio' },
	{ slug: 'gigascale', name: 'Gigascale', url: 'https://gigascale.com/portfolio/' },
	{ slug: 'glasswing', name: 'Glasswing Ventures', url: 'https://glasswing.vc/our-companies/' },
	{ slug: 'glilot', name: 'Glilot Capital', url: 'https://glilotcapital.com/portfolio/' },
	{ slug: 'gv', name: 'Google Ventures', url: 'https://www.gv.com/portfolio' },
	{ slug: 'greycroft', name: 'Greycroft', url: 'https://www.greycroft.com/portfolio/' },
	{ slug: 'greylock', name: 'Greylock', url: 'https://greylock.com/portfolio/' },
	{ slug: 'grove', name: 'Grove Ventures', url: 'https://www.grovevc.com/grove-portfolio-companies/' },
	{ slug: 'headline', name: 'Headline', url: 'https://headline.com/portfolio' },
	{ slug: 'htgf', name: 'HTGF', url: 'https://www.htgf.de/en/portfolio/' },
	{ slug: 'hvcapital', name: 'HV Capital', url: 'https://www.hvcapital.com/portfolio' },
	{ slug: 'indexventures', name: 'Index Ventures', url: 'https://www.indexventures.com/companies/backed/all/' },
	{ slug: 'indiebio', name: 'Indie Bio', url: 'https://indiebio.co/' },
	{ slug: 'industrifonden', name: 'Industrifonden', url: 'https://industrifonden.com/portfolio/' },
	{ slug: 'initialized', name: 'Initialized Capital', url: 'https://initialized.com/companies' },
	{ slug: 'innovestor', name: 'Innovestor', url: 'https://innovestorgroup.com/venture-capital/portfolio-companies/' },
	{ slug: 'inovia', name: 'Inovia Capital', url: 'https://www.inovia.vc/active-companies' },
	{ slug: 'insight', name: 'Insight Partners', url: 'https://www.insightpartners.com/portfolio/' },
	{ slug: 'invus', name: 'Invus', url: 'https://www.invus.com/invus-opportunities/#portfolio' },
	{ slug: 'ivp', name: 'IVP', url: 'https://www.ivp.com/portfolio/' },
	{ slug: 'khosla', name: 'Khosla Ventures', url: 'https://www.khoslaventures.com/portfolio/' },
	{ slug: 'kima', name: 'Kima Ventures', url: 'https://www.kimaventures.com/portfolio' },
	{ slug: 'kinnevik', name: 'Kinnevik', url: 'https://www.kinnevik.com/investments/' },
	{ slug: 'kleiner', name: 'Kleiner Perkins', url: 'https://jobs.kleinerperkins.com/companies' },
	{ slug: 'kurma', name: 'Kurma Partners', url: 'https://www.kurmapartners.com/en/portfolio' },
	{ slug: 'lakestar', name: 'Lakestar', url: 'https://www.lakestar.com/funds' },
	{ slug: 'lifeline', name: 'Lifeline Ventures', url: 'https://www.lifelineventures.com/companies/' },
	{ slug: 'lightspeed', name: 'Lightspeed Ventures', url: 'https://lsvp.com/companies/' },
	{ slug: 'lux', name: 'Lux Capital', url: 'https://www.luxcapital.com/companies' },
	{ slug: 'menlo', name: 'Menlo Ventures', url: 'https://menlovc.com/portfolio/' },
	{ slug: 'mig', name: 'MIG Capital', url: 'https://www.mig.ag/en/portfolio/' },
	{ slug: 'mouro', name: 'Mouro Capital', url: 'https://www.mourocapital.com/our-portfolio/' },
	{ slug: 'nea', name: 'NEA', url: 'https://www.nea.com/portfolio?category=all' },
	{ slug: 'nexus', name: 'Nexus Venture Partners', url: 'https://nexusvp.com/companies/' },
	{ slug: 'northzone', name: 'Northzone', url: 'https://northzone.com/portfolio' },
	{ slug: 'norwest', name: 'Norwest', url: 'https://www.norwest.com/companies' },
	{ slug: 'octopus', name: 'Octopus Ventures', url: 'https://octopusventures.com/portfolio/' },
	{ slug: 'oneequity', name: 'OneEquity', url: 'https://www.oneequity.com/portfolio' },
	{ slug: 'openocean', name: 'OpenOcean', url: 'https://www.openocean.vc/portfolio' },
	{ slug: 'otb', name: 'OTB Ventures', url: 'https://otb.vc/portfolio/' },
	{ slug: 'palladium', name: 'Palladium', url: 'https://www.palladiumequity.com/investments' },
	{ slug: 'pear', name: 'Pear VC', url: 'https://pear.vc/companies/' },
	{ slug: 'pillar', name: 'Pillar VC', url: 'https://www.pillar.vc/companies/' },
	{ slug: 'pitango', name: 'Pitango', url: 'https://www.pitango.com/portfolio/' },
	{ slug: 'plugandplay', name: 'Plug and Play', url: 'https://www.plugandplaytechcenter.com/innovation-services/startups/our-startups' },
	{ slug: 'plural', name: 'Plural', url: 'https://www.pluralplatform.com/portfolio' },
	{ slug: 'pointnine', name: 'Point Nine', url: 'https://www.pointnine.com/companies' },
	{ slug: 'polaris', name: 'Polaris Partners', url: 'https://polarispartners.com/companies-list' },
	{ slug: 'prelude', name: 'Prelude Ventures', url: 'https://www.preludeventures.com/portfolio' },
	{ slug: 'push', name: 'PUSH VC', url: 'https://push.vc/portfolio' },
	{ slug: 'qed', name: 'QED Investors', url: 'https://www.qedinvestors.com/companies' },
	{ slug: 'quantonation', name: 'Quantonation', url: 'https://www.quantonation.com/portfolio/' },
	{ slug: 'qumra', name: 'Qumra Capital', url: 'https://qumracapital.com/portfolio/' },
	{ slug: 'racap', name: 'RA Capital', url: 'https://www.racap.com/portfolio' },
	{ slug: 'recall', name: 'Recall Capital', url: 'https://www.recall.capital/portfolio' },
	{ slug: 'redpoint', name: 'Redpoint', url: 'https://www.redpoint.com/companies/' },
	{ slug: 'salesforce', name: 'Salesforce Ventures', url: 'https://salesforceventures.com/portfolio/' },
	{ slug: 'sapphire', name: 'Sapphire Ventures', url: 'https://sapphireventures.com/companies/' },
	{ slug: 'seedcamp', name: 'Seedcamp', url: 'https://seedcamp.com/our-companies/' },
	{ slug: 'sequoia', name: 'Sequoia Capital', url: 'https://www.sequoiacap.com/our-companies/' },
	{ slug: 'silversmith', name: 'Silversmith', url: 'https://www.silversmith.com/portfolio' },
	{ slug: 'slow', name: 'Slow Ventures', url: 'https://slow.co/about/' },
	{ slug: 'sosv', name: 'SOSV', url: 'https://sosv.com/portfolio/' },
	{
		slug: 'southparkcommons',
		name: 'South Park Commons',
		url: 'https://www.southparkcommons.com/companies'
	},
	{ slug: 'spark', name: 'Spark Capital', url: 'https://www.sparkcapital.com/companies' },
	{ slug: 'speedinvest', name: 'Speedinvest', url: 'https://www.speedinvest.com/portfolio' },
	{ slug: 'stageone', name: 'StageOne Ventures', url: 'https://stageonevc.com/portfolio/' },
	{
		slug: 'standardindustries',
		name: 'Standard Industries',
		url: 'https://standardindustries.com/our-businesses/standard-investments/venture-capital'
	},
	{ slug: 'stripes', name: 'Stripes', url: 'https://www.stripes.co/investments#sort=all' },
	{ slug: 'superhero', name: 'Superhero', url: 'https://superherocapital.com/portfolio/' },
	{ slug: 'svangel', name: 'SV Angel', url: 'https://svangel.com/portfolio' },
	{ slug: 'targetglobal', name: 'Target Global', url: 'https://www.targetglobal.vc/portfolio' },
	{ slug: 'tcv', name: 'TCV', url: 'https://www.tcv.com/partnerships' },
	{ slug: 'team8', name: 'Team8', url: 'https://team8.vc/portfolio/' },
	{ slug: 'techstars', name: 'Techstars', url: 'https://www.techstars.com/portfolio' },
	{ slug: 'thomabravo', name: 'Thoma Bravo', url: 'https://www.thomabravo.com/portfolio' },
	{ slug: 'tlv', name: 'TLV Partners', url: 'https://tlv.partners/portfolio/' },
	{ slug: 'townhall', name: 'Town Hall Ventures', url: 'https://www.townhallventures.com/portfolio' },
	{ slug: 'transformation', name: 'Transformation Capital', url: 'https://transformcap.com/partner-companies' },
	{
		slug: 'trianglepeak',
		name: 'Triangle Peak',
		url: 'https://www.trianglepeakpartners.com/technology/'
	},
	{ slug: 'uncork', name: 'Uncork Capital', url: 'https://uncorkcapital.com/companies/' },
	{ slug: 'usv', name: 'Union Square Ventures', url: 'https://www.usv.com/companies/' },
	{ slug: 'venrock', name: 'Venrock', url: 'https://www.venrock.com/companies/' },
	{
		slug: 'vertex',
		name: 'Vertex Ventures Israel',
		url: 'https://www.vertexventures.co.il/#portfolio'
	},
	{ slug: 'viking', name: 'Viking', url: 'https://vikingglobal.com/private-equity-portfolio/' },
	{ slug: 'viola', name: 'Viola', url: 'https://www.viola-group.com/portfolio/' },
	{
		slug: 'wellington',
		name: 'Wellington',
		url: 'https://www.wellington.com/en/capabilities/private-investing/our-investments'
	},
	{ slug: 'wischoff', name: 'Wischoff Ventures', url: 'https://www.wischoff.com/' },
	{
		slug: 'worklife',
		name: 'Worklife Ventures',
		url: 'https://www.worklife.vc/companies'
	},
	{ slug: 'worldfund', name: 'World Fund', url: 'https://www.worldfund.vc/portfolio' },
	{
		slug: 'wvvcapital',
		name: 'WVV Capital',
		url: 'https://www.wvvcapital.com/portfolio-companies'
	},
	{ slug: 'wxrfund', name: 'WXR Fund', url: 'https://www.wxrfund.com/portfolio' },
	{ slug: 'xange', name: 'XAnge', url: 'https://www.xange.vc/portfolio' },
	{
		slug: 'xfactorventures',
		name: 'XFactor Ventures',
		url: 'https://www.xfactor.ventures/portfolio'
	},
	{ slug: 'xfund', name: 'Xfund', url: 'https://www.xfund.com/portfolio' },
	{
		slug: 'xrcventures',
		name: 'XRC Ventures',
		url: 'https://www.xrcventures.com/portfolio'
	},
	{ slug: 'xyz', name: 'XYZ', url: 'https://www.xyz.vc/portfolio' },
	{ slug: 'ycombinator', name: 'Y Combinator', url: 'https://www.ycombinator.com/companies' },
	{ slug: 'yesvc', name: 'Yes VC', url: 'https://yes.vc/portfolio/' },
	{ slug: 'ylventures', name: 'YL Ventures', url: 'https://www.ylventures.com/portfolio/' },
	{ slug: 'zcg', name: 'ZCG', url: 'https://www.zcg.com/portfolio' },
	{
		slug: 'zeal',
		name: 'Zeal Capital Partners',
		url: 'https://www.zealcapitalpartners.com/portfolio/'
	},
	{ slug: 'zenda', name: 'Zenda', url: 'https://www.zenda.vc/portfolio/' },
	{ slug: 'zetta', name: 'Zetta Venture Partners', url: 'https://www.zettavp.com/companies' },
	{ slug: 'zigg', name: 'Zigg Capital', url: 'https://ziggcap.com/#portfolio' }
];

export const fundName = new Map(FUNDS.map((f) => [f.slug, f.name]));
export const fundBySlug = new Map(FUNDS.map((f) => [f.slug, f]));
