// The 661 tracked funds, in case-insensitive alphabetical order by name — the
// dashboard, the timeline and the download list them in this order. Slugs
// match the scraper module filenames in
// src/server/scrapers/; display names come from scrapa/all.json (with the
// "General Catalys" typo fixed and Octopus Ventures added). url is the fund's
// public portfolio page (for the API-based scrapers it's the human-facing
// equivalent of the scraped endpoint).
export interface FundInfo {
	slug: string;
	name: string;
	url: string;
}

export const FUNDS: FundInfo[] = [
	{ slug: '01a', name: '01A', url: 'https://01a.com/portfolio' },
	{ slug: '10d', name: '10D', url: 'https://www.10d.vc/portfolio/' },
	{ slug: 'twentyvc', name: '20VC', url: 'https://20vc.fund/portfolio' },
	{ slug: '2150', name: '2150', url: 'https://www.2150.vc/investments' },
	{ slug: '3vc', name: '3VC', url: 'https://three.vc/portfolio/' },
	{ slug: '500', name: '500 Global', url: 'https://500.co/portfolio' },
	{ slug: '7percent', name: '7percent', url: 'https://www.7pc.vc/portfolio' },
	{ slug: '83north', name: '83North', url: 'https://www.83north.com/companies/' },
	{ slug: 'acapital', name: 'A Capital', url: 'https://acapital.com/portfolio' },
	{ slug: 'accel', name: 'Accel', url: 'https://www.accel.com/companies' },
	{ slug: 'actions', name: 'Actions Capital', url: 'https://www.actions.capital/founders' },
	{ slug: 'advent', name: 'Advent International', url: 'https://www.adventinternational.com/investments/' },
	{
		slug: 'airbusventures',
		name: 'Airbus Ventures',
		url: 'https://www.airbusventures.vc/portfolio'
	},
	{ slug: 'aisling', name: 'Aisling Capital', url: 'https://www.aislingcapital.com/portfolio' },
	{
		slug: 'alchemist',
		name: 'Alchemist Accelerator',
		url: 'https://www.alchemistaccelerator.com/portfolio'
	},
	{ slug: 'aleph', name: 'Aleph', url: 'https://www.aleph.vc/companies' },
	{ slug: 'alumni', name: 'Alumni Ventures', url: 'https://www.av.vc/portfolio' },
	{ slug: 'ambition', name: 'Ambition Capital', url: 'https://www.ambition.capital/portfolio' },
	{ slug: 'a16z', name: 'Andreessen Horowitz', url: 'https://a16z.com/portfolio/' },
	{ slug: 'antler', name: 'Antler', url: 'https://www.antler.co/portfolio' },
	{ slug: 'apex', name: 'Apex Ventures', url: 'https://www.apex.ventures/portfolio' },
	{ slug: 'archventure', name: 'ARCH Venture Partners', url: 'https://archventure.com/portfolio/' },
	{ slug: 'atlas', name: 'Atlas Venture', url: 'https://atlasventure.com/portfolio/' },
	{ slug: 'av8', name: 'AV8', url: 'https://av8.vc/our-portfolio/' },
	{ slug: 'avp', name: 'AVP', url: 'https://avpcap.com/companies/' },
	{ slug: 'aws', name: 'aws', url: 'https://www.gruendungsfonds.at/portfolio' },
	{ slug: 'b2venture', name: 'b2venture', url: 'https://www.b2venture.vc/portfolio' },
	{ slug: 'baincapital', name: 'Bain Capital Ventures', url: 'https://baincapitalventures.com/portfolio/' },
	{ slug: 'balderton', name: 'Balderton', url: 'https://www.balderton.com/companies/' },
	{ slug: 'base10', name: 'Base10', url: 'https://base10.vc/' },
	{ slug: 'battery', name: 'Battery Ventures', url: 'https://www.battery.com/company/' },
	{ slug: 'behold', name: 'Behold Ventures', url: 'https://behold.vc/portfolio' },
	{ slug: 'bessemer', name: 'Bessemer Venture Partners', url: 'https://www.bvp.com/companies' },
	{ slug: 'bip', name: 'BIP Ventures', url: 'https://www.bipventures.vc/portfolio' },
	{ slug: 'bluventures', name: 'Blu Ventures', url: 'https://www.bluventureinvestors.com/portfolio' },
	{ slug: 'boxgroup', name: 'BoxGroup', url: 'https://www.boxgroup.com/portfolio' },
	{ slug: 'breakthrough', name: 'Breakthrough Energy', url: 'https://www.breakthroughenergy.org/portfolio/index.html' },
	{ slug: 'broocknell', name: 'Broocknell Ventures', url: 'https://broocknell.com/all-projects/' },
	{ slug: 'calmstorm', name: 'Calm/Storm', url: 'https://www.calmstorm.vc/portfolio' },
	{ slug: 'canapi', name: 'Canapi', url: 'https://www.canapi.com/portfolio' },
	{ slug: 'cherry', name: 'Cherry Ventures', url: 'https://www.cherry.vc/founders' },
	{ slug: 'congruent', name: 'Congruent Ventures', url: 'https://www.congruentvc.com/portfolio' },
	{ slug: 'craft', name: 'Craft Ventures', url: 'https://www.craftventures.com/portfolio' },
	{ slug: 'creandum', name: 'Creandum', url: 'https://creandum.com/commitments/' },
	{ slug: 'credo', name: 'Credo', url: 'https://www.credoventures.com/portfolio' },
	{ slug: 'crush', name: 'Crush Ventures', url: 'https://crush.ventures/#companies-anchor' },
	{ slug: 'crv', name: 'CRV', url: 'https://www.crv.com/companies' },
	{ slug: 'cti', name: 'CTI Life Sciences Fund', url: 'https://www.ctisciences.com/portfolio' },
	{ slug: 'cultivian', name: 'Cultivian Sandbox Ventures', url: 'https://cultiviansbx.com/portfolio' },
	{ slug: 'cybernetix', name: 'Cybernetix Ventures', url: 'https://cybernetix.vc/#portfolio' },
	{ slug: 'cyberstarts', name: 'Cyberstarts', url: 'https://www.cyberstarts.com/portfolio' },
	{ slug: 'dayone', name: 'Day One Ventures', url: 'https://www.dayoneventures.com/#portfolio' },
	{ slug: 'dcvc', name: 'DCVC', url: 'https://www.dcvc.com/companies' },
	{ slug: 'debut', name: 'Debut Capital', url: 'https://debutcapital.com/portfolio' },
	{ slug: 'decibel', name: 'Decibel', url: 'https://www.decibel.vc/companies' },
	{ slug: 'deciens', name: 'Deciens Capital', url: 'https://deciens.com/companies' },
	{ slug: 'decisivepoint', name: 'Decisive Point', url: 'https://www.decisivepoint.com/portfolio' },
	{ slug: 'define', name: 'Define Ventures', url: 'https://www.definevc.com/partners' },
	{ slug: 'defy', name: 'Defy', url: 'https://defy.vc/companies/' },
	{ slug: 'designerfund', name: 'Designer Fund', url: 'https://designerfund.com/companies' },
	{ slug: 'dfs', name: 'DFS', url: 'https://www.dfs.vc/portfolio.html' },
	{ slug: 'differential', name: 'Differential Ventures', url: 'https://www.differential.vc/portfolio' },
	{ slug: 'digitalis', name: 'Digitalis Ventures', url: 'https://www.digitalisventures.com/human-health' },
	{ slug: 'digitx', name: 'DigitX Partners', url: 'https://www.digitxpartners.com/portfolio' },
	{ slug: 'distributed', name: 'Distributed Ventures', url: 'https://www.distributedvc.com/portfolio' },
	{ slug: 'divergent', name: 'Divergent Capital', url: 'https://www.divergenthq.com/#portfolio' },
	{ slug: 'dragonfly', name: 'Dragonfly', url: 'https://dragonfly.com/#portfolio' },
	{ slug: 'draper', name: 'Draper Associates', url: 'https://www.draper.vc/portfolio' },
	{ slug: 'dreamers', name: 'Dreamers VC', url: 'https://www.dreamers.vc/portolio' },
	{ slug: 'dreamit', name: 'Dreamit Ventures', url: 'https://www.dreamit.com/portfolio-securetech' },
	{ slug: 'drive', name: 'Drive Capital', url: 'https://drivecapital.com/portfolio' },
	{ slug: 'dynamo', name: 'Dynamo Ventures', url: 'https://dynamo.vc/startup-investment-portfolio' },
	{ slug: 'e14', name: 'E14', url: 'https://www.e14.vc/companies' },
	{ slug: 'e2mc', name: 'E2MC', url: 'https://e2mc.space/portfolio' },
	{ slug: 'earlylight', name: 'Early Light Ventures', url: 'https://www.earlylight.vc/portfolio' },
	{ slug: 'earlybird', name: 'Earlybird', url: 'https://earlybird.com/companies' },
	{ slug: 'eastlink', name: 'Eastlink Capital', url: 'https://www.eastlinkcap.com/portfolio/' },
	{ slug: 'echovc', name: 'EchoVC Partners', url: 'https://www.echovc.com/ourportfolio' },
	{ slug: 'eclipse', name: 'Eclipse Ventures', url: 'https://eclipse.capital/companies' },
	{ slug: 'ecliptic', name: 'Ecliptic Capital', url: 'https://www.ecliptic.capital/portfolio' },
	{ slug: 'ecp', name: 'ECP Growth', url: 'https://ecpgrowth.com/portfolio/' },
	{ slug: 'edovate', name: 'Edovate Capital', url: 'https://edovatecapital.com/portfolio/' },
	{ slug: 'educapital', name: 'Educapital', url: 'https://www.educapitalvc.com/portfolio' },
	{ slug: 'eif', name: 'Education Impact Fund', url: 'https://www.educationimpactfund.org/portfolio/' },
	{ slug: 'elaia', name: 'Elaia', url: 'https://elaia.com/portfolio' },
	{ slug: 'electric', name: 'Electric Capital', url: 'https://www.electriccapital.com/investments/' },
	{ slug: 'elementum', name: 'Elementum Ventures', url: 'https://elementum.vc/companies' },
	{ slug: 'elevate', name: 'Elevate Ventures', url: 'https://elevateventures.com/portfolio/' },
	{ slug: 'elizabethstreet', name: 'Elizabeth Street Ventures', url: 'https://elizabethstreet.vc/#portfolio-anchor' },
	{ slug: 'emerging', name: 'Emerging Ventures', url: 'https://emerging.vc/portfolio' },
	{ slug: 'eip', name: 'Energy Impact Partners', url: 'https://www.energyimpactpartners.com/_portfolio/' },
	{ slug: 'engine', name: 'Engine Ventures', url: 'https://engineventures.com/companies' },
	{ slug: 'engineeringcapital', name: 'Engineering Capital', url: 'https://www.engineeringcapital.com/#portfolio' },
	{ slug: 'eniac', name: 'Eniac Ventures', url: 'https://www.eniac.vc/companies' },
	{ slug: 'entree', name: 'Entrée Capital', url: 'https://entreecap.com/companies' },
	{ slug: 'ef', name: 'Entrepreneurs First', url: 'https://www.joinef.com/portfolio/' },
	{ slug: 'eoventures', name: 'EO Ventures', url: 'https://eoventures.com/portfolio-all' },
	{ slug: 'episode1', name: 'Episode 1', url: 'https://www.episode1.com/portfolio' },
	{ slug: 'eqt', name: 'EQT Group', url: 'https://eqtgroup.com/about/current-portfolio' },
	{ slug: 'equal', name: 'Equal Ventures', url: 'https://www.equal.vc/portfolio' },
	{ slug: 'era', name: 'Era Ventures', url: 'https://eraventures.com/companies/' },
	{ slug: 'essence', name: 'Essence Venture Capital', url: 'https://essencevc.fund/' },
	{ slug: 'exceptional', name: 'Exceptional Capital', url: 'https://www.exceptionalcap.com/portfolio' },
	{ slug: 'expa', name: 'Expa', url: 'https://www.expa.com/portfolio/' },
	{ slug: 'expansion', name: 'Expansion', url: 'https://expansion-vc.eu/portfolio' },
	{ slug: 'exponent', name: 'Exponent', url: 'https://www.exponentpe.com/our-portfolio' },
	{ slug: 'fprime', name: 'F-Prime Capital', url: 'https://www.fprimecapital.com/portfolio/' },
	{ slug: 'f2', name: 'F2 Venture Capital', url: 'https://www.f2vc.com/companies' },
	{ slug: 'f7', name: 'f7 Ventures', url: 'https://www.f7ventures.com/portfolio/' },
	{ slug: 'fcavp', name: 'FCA Venture Partners', url: 'https://www.fcavp.com/portfolio' },
	{ slug: 'felicis', name: 'Felicis', url: 'https://www.felicis.com/companies' },
	{ slug: 'femalefounders', name: 'Female Founders Fund', url: 'https://femalefoundersfund.com/portfolio/' },
	{ slug: 'fernbrook', name: 'Fernbrook', url: 'https://www.fernbrookmgmt.com/investments/' },
	{ slug: 'ffvc', name: 'ff Venture Capital', url: 'https://ffvc.com/portfolio/' },
	{ slug: 'fifthwall', name: 'Fifth Wall', url: 'https://www.fifthwall.com/portfolio' },
	{ slug: 'figure8', name: 'Figure 8', url: 'https://www.figure8.vc/#Portfolio' },
	{ slug: 'fika', name: 'Fika Ventures', url: 'https://www.fika.vc/portfolio' },
	{ slug: 'filrouge', name: 'Fil Rouge Capital', url: 'https://www.filrougecapital.com/portfolio' },
	{ slug: 'fincapital', name: 'Fin Capital', url: 'https://fin.capital/portfolio' },
	{ slug: 'fintechcollective', name: 'FinTech Collective', url: 'https://fintech.io/portfolio' },
	{ slug: 'fintechv', name: 'Fintech Ventures Fund', url: 'https://www.fintechv.com/portfolio' },
	{ slug: 'firebrand', name: 'Firebrand', url: 'https://www.firebrandvc.com/portfolio' },
	{ slug: 'firstcheque', name: 'First Cheque', url: 'https://www.firstcheque.vc/portfolio' },
	{ slug: 'firstcircle', name: 'First Circle Capital', url: 'https://www.firstcircle.capital/portfolio' },
	{ slug: 'firstin', name: 'First In', url: 'https://wearefirstin.com/#portfolio' },
	{ slug: 'firstround', name: 'First Round', url: 'https://www.firstround.com/companies' },
	{ slug: 'firststar', name: 'First Star Ventures', url: 'https://firststar.vc/companies' },
	{ slug: 'firstcheck', name: 'FirstCheck Africa', url: 'https://www.firstcheck.africa/portfolio' },
	{ slug: 'firstmark', name: 'FirstMark', url: 'https://www.firstmark.com/portfolio' },
	{ slug: 'firstminute', name: 'firstminute capital', url: 'https://www.firstminute.capital/portfolio' },
	{ slug: 'fitch', name: 'Fitch Ventures', url: 'https://www.fitchventures.com/portfolio' },
	{ slug: 'fjlabs', name: 'FJ Labs', url: 'https://www.fjlabs.com/portfolio' },
	{ slug: 'flagship', name: 'Flagship Pioneering', url: 'https://www.flagshippioneering.com/companies' },
	{ slug: 'flare', name: 'Flare Capital Partners', url: 'https://www.flarecapital.com/companies/' },
	{ slug: 'flint', name: 'Flint Capital', url: 'https://flintcap.com/' },
	{ slug: 'floodgate', name: 'Floodgate', url: 'https://www.floodgate.com/companies' },
	{ slug: 'flourish', name: 'Flourish Ventures', url: 'https://flourishventures.com/portfolio/' },
	{ slug: 'flucas', name: 'Flucas Ventures', url: 'https://www.flucasvc.com/portfolio' },
	{ slug: 'fly', name: 'Fly', url: 'https://fly.vc/portfolio' },
	{ slug: 'flybridge', name: 'Flybridge', url: 'https://www.flybridge.com/portfolio' },
	{ slug: 'focal', name: 'focal', url: 'https://focal.vc/portfolio/' },
	{ slug: 'foothill', name: 'Foothill Ventures', url: 'https://www.foothill.ventures/portfolio' },
	{ slug: 'footprintcoalition', name: 'FootPrint Coalition', url: 'https://www.footprintcoalition.com/investments' },
	{ slug: 'forerunner', name: 'Forerunner Ventures', url: 'https://www.forerunnerventures.com/investments/' },
	{ slug: 'foundamental', name: 'Foundamental', url: 'https://www.foundamental.com/portfolio' },
	{ slug: 'foundationcapital', name: 'Foundation Capital', url: 'https://foundationcapital.com/portfolio' },
	{ slug: 'foundationventures', name: 'Foundation Ventures', url: 'https://www.foundationventures.com/portfolio' },
	{ slug: 'foundercollective', name: 'Founder Collective', url: 'https://foundercollective.com/portfolio/' },
	{ slug: 'founderfuel', name: 'FounderFuel', url: 'https://founderfuel.com/companies/' },
	{ slug: 'foundersfund', name: 'Founders Fund', url: 'https://foundersfund.com/portfolio/' },
	{ slug: 'foundry', name: 'Foundry', url: 'https://foundry.vc/portfolio/' },
	{ slug: 'fouracres', name: 'Four Acres Capital', url: 'https://www.fouracres.vc/portfolio' },
	{ slug: 'fpv', name: 'FPV Ventures', url: 'https://fpvventures.com/all-companies/' },
	{ slug: 'framework', name: 'Framework Ventures', url: 'https://framework.ventures/portfolio' },
	{ slug: 'freestyle', name: 'Freestyle', url: 'https://freestyle.vc/companies' },
	{ slug: 'fcventures', name: 'Frist Cressey Ventures', url: 'https://fcventures.com/partnerships/' },
	{ slug: 'frst', name: 'Frst', url: 'https://www.frst.vc/' },
	{ slug: 'ftw', name: 'FTW Ventures', url: 'https://www.ftw.vc/companies' },
	{ slug: 'fuelcapital', name: 'Fuel Capital', url: 'https://www.fuelcapital.com/portfolio' },
	{ slug: 'fuelvc', name: 'Fuel Venture Capital', url: 'https://fuelventurecapital.com/portfolio' },
	{ slug: 'fuelventures', name: 'Fuel Ventures', url: 'https://www.fuel.ventures/portfolio' },
	{ slug: 'further', name: 'Further Ventures', url: 'https://ventures.further.ae/companies' },
	{ slug: 'fusionfund', name: 'Fusion Fund', url: 'https://www.fusionfund.com/portfolio' },
	{ slug: 'futureafrica', name: 'Future Africa', url: 'https://www.future.africa/companies' },
	{ slug: 'futurefood', name: 'Future Food Fund', url: 'https://futurefoodfund.nl/portfolio/' },
	{ slug: 'futureperfect', name: 'Future Perfect Ventures', url: 'https://www.futureperfectventures.com/invest' },
	{ slug: 'futurepositive', name: 'Future Positive Capital', url: 'https://www.futurepositivecapital.com/companies' },
	{ slug: 'futureventures', name: 'Future Ventures', url: 'https://future.ventures/investments' },
	{ slug: 'g2', name: 'G2', url: 'https://www.g2vp.com/portfolio' },
	{ slug: 'gaingels', name: 'Gaingels', url: 'https://gaingels.com/#homePortfolio' },
	{ slug: 'gway', name: 'Gateway Capital', url: 'https://gwaycapital.com/portfolio/' },
	{ slug: 'geek', name: 'Geek Ventures', url: 'https://geek.vc/portfolio' },
	{ slug: 'generalatlantic', name: 'General Atlantic', url: 'https://www.generalatlantic.com/investments/' },
	{ slug: 'generalcatalyst', name: 'General Catalyst', url: 'https://www.generalcatalyst.com/portfolio' },
	{ slug: 'genesia', name: 'Genesia Ventures', url: 'https://www.genesiaventures.com/en/partners/' },
	{ slug: 'gfr', name: 'GFR Fund', url: 'https://gfrfund.com/portfolio' },
	{ slug: 'giant', name: 'Giant Ventures', url: 'https://www.giant.vc/portfolio' },
	{ slug: 'gigascale', name: 'Gigascale', url: 'https://gigascale.com/portfolio/' },
	{ slug: 'gingerbread', name: 'Gingerbread Capital', url: 'https://gingerbreadcap.com/portfolio/' },
	{ slug: 'glasswing', name: 'Glasswing Ventures', url: 'https://glasswing.vc/our-companies/' },
	{ slug: 'glilot', name: 'Glilot Capital', url: 'https://glilotcapital.com/portfolio/' },
	{ slug: 'goahead', name: 'GoAhead Ventures', url: 'https://www.goaheadvc.com/en/portfolio-all' },
	{ slug: 'gobi', name: 'Gobi Partners', url: 'https://www.gobi.vc/portfolio' },
	{ slug: 'goldhouse', name: 'Gold House Ventures', url: 'https://goldhouse.org/ghv-companies/' },
	{ slug: 'goldengate', name: 'Golden Gate Ventures', url: 'https://www.goldengate.vc/portfolio' },
	{ slug: 'goldenpalm', name: 'Golden Palm Investments', url: 'https://www.gpalminvestments.org/portfolio' },
	{ slug: 'goldenseeds', name: 'Golden Seeds', url: 'https://www.goldenseeds.com/our-companies' },
	{ slug: 'gv', name: 'Google Ventures', url: 'https://www.gv.com/portfolio' },
	{ slug: 'gorilla', name: 'Gorilla Capital', url: 'https://gorillacapital.fi/portfolio/' },
	{ slug: 'gradient', name: 'Gradient Ventures', url: 'https://www.gradient.com/portfolio/' },
	{ slug: 'graniteasia', name: 'Granite Asia', url: 'https://www.graniteasia.com/portfolio' },
	{ slug: 'graph', name: 'Graph Ventures', url: 'https://www.graphventures.com/#companies' },
	{ slug: 'greatoaks', name: 'Great Oaks Venture Capital', url: 'https://www.greatoaksvc.com/portfolio' },
	{ slug: 'greatpoint', name: 'GreatPoint Ventures', url: 'https://www.gpv.com/companies' },
	{ slug: 'greenegg', name: 'Green Egg Ventures', url: 'https://greenegg.vc/#portfolio' },
	{ slug: 'greenmeadow', name: 'Green Meadow Ventures', url: 'https://www.greenmeadow.co/portfolio' },
	{ slug: 'greycroft', name: 'Greycroft', url: 'https://www.greycroft.com/portfolio/' },
	{ slug: 'greylock', name: 'Greylock', url: 'https://greylock.com/portfolio/' },
	{ slug: 'groundup', name: 'GroundUp', url: 'https://www.groundup.vc/portfolio' },
	{ slug: 'group11', name: 'Group 11', url: 'https://group11.vc/portfolio/' },
	{ slug: 'grove', name: 'Grove Ventures', url: 'https://www.grovevc.com/grove-portfolio-companies/' },
	{ slug: 'gsv', name: 'GSV Ventures', url: 'https://gsv.ventures/portfolio/' },
	{ slug: 'gtmfund', name: 'GTMfund', url: 'https://www.gtmfund.com/portfolio/' },
	{ slug: 'gula', name: 'Gula Tech Adventures', url: 'https://www.gula.tech/portfolio' },
	{ slug: 'halogen', name: 'Halogen Ventures', url: 'https://halogenvc.com/portfolio' },
	{ slug: 'hannahgrey', name: 'Hannah Grey', url: 'https://www.hannahgrey.com/portfolio-1' },
	{ slug: 'harlem', name: 'Harlem Capital', url: 'https://harlem.capital/portfolio/' },
	{ slug: 'haun', name: 'Haun Ventures', url: 'https://www.haun.co/portfolio' },
	{ slug: 'hax', name: 'HAX', url: 'https://hax.co/startups/' },
	{ slug: 'haystack', name: 'Haystack', url: 'https://haystack.vc/portfolio' },
	{ slug: 'hcvc', name: 'HCVC', url: 'https://www.hcvc.co/pages/portfolio' },
	{ slug: 'headline', name: 'Headline', url: 'https://headline.com/portfolio' },
	{ slug: 'healthx', name: 'HealthX Ventures', url: 'https://www.healthxventures.com/portfolio' },
	{ slug: 'healthy', name: 'Healthy Ventures', url: 'https://healthy.vc/portfolio' },
	{ slug: 'hearstlab', name: 'HearstLab', url: 'https://www.hearstlab.com/portfolio' },
	{ slug: 'heartcore', name: 'Heartcore Capital', url: 'https://www.heartcore.com/companies' },
	{ slug: 'heavybit', name: 'Heavybit', url: 'https://www.heavybit.com/portfolio' },
	{ slug: 'helios', name: 'Helios Capital', url: 'https://www.helioscapital.us/portfolio-2/' },
	{ slug: 'helium3', name: 'Helium-3 Ventures', url: 'https://www.helium-3ventures.com/#portfolio' },
	{ slug: 'hetz', name: 'Hetz Ventures', url: 'https://www.hetz.vc/our-portfolio' },
	{ slug: 'hofcapital', name: 'HOF Capital', url: 'https://hofcapital.com/portfolio' },
	{ slug: 'homebrew', name: 'Homebrew', url: 'https://www.homebrew.co/#Portfolio' },
	{ slug: 'horizons', name: 'Horizons Ventures', url: 'https://www.horizonsventures.com/portfolio' },
	{ slug: 'howwomeninvest', name: 'How Women Invest', url: 'https://www.howwomeninvest.com/portfolio' },
	{ slug: 'htgf', name: 'HTGF', url: 'https://www.htgf.de/en/portfolio/' },
	{ slug: 'humancapital', name: 'Human Capital', url: 'https://human.capital/portfolio' },
	{ slug: 'hummingbird', name: 'Hummingbird Ventures', url: 'https://www.hummingbird.vc/portfolio' },
	{ slug: 'hvcapital', name: 'HV Capital', url: 'https://www.hvcapital.com/portfolio' },
	{ slug: 'hyperplane', name: 'Hyperplane', url: 'https://www.hyperplane.vc/companies' },
	{ slug: 'illuminate', name: 'Illuminate Financial', url: 'https://www.illuminatefinancial.com/portfolio' },
	{ slug: 'imaginary', name: 'Imaginary Ventures', url: 'https://www.imaginary.co/companies' },
	{ slug: 'impactamerica', name: 'Impact America Fund', url: 'https://impactamericafund.com/portfolio' },
	{ slug: 'incisive', name: 'Incisive Ventures', url: 'https://incisive.vc/investments/' },
	{ slug: 'indexventures', name: 'Index Ventures', url: 'https://www.indexventures.com/companies/backed/all/' },
	{ slug: 'indiebio', name: 'Indie Bio', url: 'https://indiebio.co/' },
	{ slug: 'industrifonden', name: 'Industrifonden', url: 'https://industrifonden.com/portfolio/' },
	{ slug: 'industrious', name: 'Industrious Ventures', url: 'https://industrious.vc/portfolio/' },
	{ slug: 'inertia', name: 'Inertia', url: 'https://inertia.vc/portfolio' },
	{ slug: 'inflecthealth', name: 'Inflect Health', url: 'https://www.inflect.health/capital' },
	{ slug: 'initialized', name: 'Initialized Capital', url: 'https://initialized.com/companies' },
	{ slug: 'innospark', name: 'Innospark Ventures', url: 'https://innospark.vc/portfolio/' },
	{ slug: 'innovatingcapital', name: 'Innovating Capital', url: 'https://innovating.capital/companies/' },
	{
		slug: 'innovationendeavors',
		name: 'Innovation Endeavors',
		url: 'https://www.innovationendeavors.com/companies'
	},
	{
		slug: 'innovationindustries',
		name: 'Innovation Industries',
		url: 'https://www.innovationindustries.com/portfolio'
	},
	{ slug: 'innovestor', name: 'Innovestor', url: 'https://innovestorgroup.com/venture-capital/portfolio-companies/' },
	{ slug: 'insight', name: 'Insight Partners', url: 'https://www.insightpartners.com/portfolio/' },
	{ slug: 'inspired', name: 'Inspired Capital', url: 'https://www.inspiredcapital.com/portfolio' },
	{ slug: 'intelcapital', name: 'Intel Capital', url: 'https://www.intelcapital.com/portfolio/' },
	{ slug: 'interlace', name: 'Interlace Ventures', url: 'https://www.interlacevc.com/portfolio' },
	{ slug: 'invus', name: 'Invus', url: 'https://www.invus.com/invus-opportunities/#portfolio' },
	{ slug: 'ironspring', name: 'Ironspring Ventures', url: 'https://ironspring.com/portfolio-companies/' },
	{ slug: 'isai', name: 'ISAI', url: 'https://www.isai.vc/portfolio' },
	{ slug: 'ivp', name: 'IVP', url: 'https://www.ivp.com/portfolio/' },
	{ slug: 'jamfund', name: 'JAM Fund', url: 'https://jamfund.com/' },
	{ slug: 'javelin', name: 'Javelin Venture Partners', url: 'https://www.javelinvp.com/companies' },
	{ slug: 'jazz', name: 'Jazz Venture Partners', url: 'https://jazzvp.com/#portfolio' },
	{ slug: 'jllspark', name: 'JLL Spark', url: 'https://spark.jllt.com/portfolio/' },
	{ slug: 'joule', name: 'Joule Ventures', url: 'https://www.joulevc.com/portfolio' },
	{ slug: 'jovono', name: 'Jovono', url: 'https://www.jovono.com/portfolio' },
	{ slug: 'juniper', name: 'Juniper VC', url: 'https://www.junipervc.com/portfolio' },
	{ slug: 'juvo', name: 'Juvo Ventures', url: 'https://juvovc.org/portfolio/' },
	{ slug: 'k5', name: 'K5 Global', url: 'https://www.k5global.com/companies' },
	{ slug: 'k9', name: 'K9 Ventures', url: 'https://www.k9ventures.com/startups/' },
	{ slug: 'kapor', name: 'Kapor Capital', url: 'https://www.kaporcapital.com/portfolio/' },
	{ slug: 'kdt', name: 'KdT Ventures', url: 'https://www.kdtvc.com/portfolio' },
	{ slug: 'khosla', name: 'Khosla Ventures', url: 'https://www.khoslaventures.com/portfolio/' },
	{ slug: 'kickstart', name: 'Kickstart Fund', url: 'https://kickstart.com/portfolio' },
	{ slug: 'kima', name: 'Kima Ventures', url: 'https://www.kimaventures.com/portfolio' },
	{ slug: 'kindred', name: 'Kindred Ventures', url: 'https://kindredventures.com/portfolio/' },
	{ slug: 'kinnevik', name: 'Kinnevik', url: 'https://www.kinnevik.com/investments/' },
	{ slug: 'kittyhawk', name: 'KittyHawk Ventures', url: 'https://www.kittyhawkvc.com/investments-portfolio' },
	{ slug: 'kleiner', name: 'Kleiner Perkins', url: 'https://jobs.kleinerperkins.com/companies' },
	{ slug: 'konvoy', name: 'Konvoy', url: 'https://www.konvoy.vc/portfolio' },
	{ slug: 'kurma', name: 'Kurma Partners', url: 'https://www.kurmapartners.com/en/portfolio' },
	{ slug: 'laconia', name: 'Laconia', url: 'https://www.laconiacapitalgroup.com/portfolio' },
	{ slug: 'lakehouse', name: 'Lakehouse Ventures', url: 'https://lakehouse.vc/portfolio/' },
	{ slug: 'lakestar', name: 'Lakestar', url: 'https://www.lakestar.com/funds' },
	{ slug: 'launchny', name: 'Launch NY', url: 'https://launchny.org/portfolio/' },
	{ slug: 'ldv', name: 'LDV Capital', url: 'https://www.ldv.co/capital' },
	{ slug: 'leadout', name: 'Leadout Capital', url: 'https://www.leadoutcapital.com/portfolio' },
	{ slug: 'learncapital', name: 'Learn Capital', url: 'https://www.learn.vc/ventures' },
	{ slug: 'learnstart', name: 'LearnStart', url: 'https://www.learnstart.vc/portfolio' },
	{ slug: 'leftlane', name: 'Left Lane Capital', url: 'https://www.leftlane.com/companies' },
	{ slug: 'lererhippeau', name: 'Lerer Hippeau', url: 'https://www.lererhippeau.com/portfolio' },
	{ slug: 'lifeforce', name: 'Lifeforce Capital', url: 'https://www.lifeforcecap.com/portfolio' },
	{ slug: 'lifeline', name: 'Lifeline Ventures', url: 'https://www.lifelineventures.com/companies/' },
	{ slug: 'lightbank', name: 'Lightbank', url: 'https://www.lightbank.com/companies' },
	{ slug: 'lightspeed', name: 'Lightspeed Ventures', url: 'https://lsvp.com/companies/' },
	{ slug: 'linkventures', name: 'Link Ventures', url: 'https://www.linkventures.com/portfolio' },
	{ slug: 'localglobe', name: 'LocalGlobe', url: 'https://www.phoenixcourt.vc/companies?fund=localglobe' },
	{ slug: 'lookingglass', name: 'Looking Glass Capital', url: 'https://lookingglass.vc/investments' },
	{ slug: 'longjourney', name: 'Long Journey Ventures', url: 'https://www.longjourney.vc/portfolio' },
	{ slug: 'lorimer', name: 'Lorimer Ventures', url: 'https://www.lorimerventures.com/portfolio' },
	{ slug: 'lowercarbon', name: 'Lowercarbon Capital', url: 'https://lowercarbon.com/companies/' },
	{ slug: 'lux', name: 'Lux Capital', url: 'https://www.luxcapital.com/companies' },
	{ slug: 'lyticalventures', name: 'Lytical Ventures', url: 'https://www.lyticalventures.com/companies' },
	{ slug: 'm12', name: 'M12', url: 'https://m12.vc/portfolio/' },
	{ slug: 'm13', name: 'M13', url: 'https://www.m13.co/portfolio' },
	{ slug: 'm1c', name: 'M1C', url: 'https://m1c.vc/portfolio' },
	{ slug: 'mac', name: 'MAC Venture Capital', url: 'https://macventurecapital.com/portfolio/' },
	{ slug: 'magic', name: 'MAGIC Fund', url: 'https://www.magic.fund/' },
	{ slug: 'mainsequence', name: 'Main Sequence', url: 'https://www.mseq.vc/all-companies' },
	{ slug: 'makers', name: 'Makers Fund', url: 'https://www.makersfund.com/portfolio' },
	{ slug: 'mana', name: 'Mana Ventures', url: 'https://www.manaventures.vc/portfolio' },
	{ slug: 'mango', name: 'Mango Capital', url: 'https://www.mangocapitalinc.com/' },
	{ slug: 'mantis', name: 'Mantis VC', url: 'https://www.mantisvc.com/portfolio' },
	{ slug: 'maple', name: 'Maple VC', url: 'https://maplevc.com/portfolio' },
	{ slug: 'massive', name: 'Massive', url: 'https://massive.vc/' },
	{ slug: 'massmutual', name: 'MassMutual Ventures', url: 'https://massmutualventures.com/portfolio/' },
	{ slug: 'material', name: 'Material Impact', url: 'https://www.materialimpact.com/companies/' },
	{ slug: 'matrix', name: 'Matrix Partners', url: 'https://matrix.vc/#portfolio' },
	{ slug: 'maverick', name: 'Maverick Ventures', url: 'https://www.maverickcapital.com/venturesportfolio' },
	{ slug: 'maveron', name: 'Maveron', url: 'https://www.maveron.com/portfolio' },
	{ slug: 'mayfield', name: 'Mayfield', url: 'https://www.mayfield.com/meet-our-founders/' },
	{ slug: 'mcj', name: 'MCJ Collective', url: 'https://mcj.vc/capital#portfolio' },
	{ slug: 'mmv', name: 'MedMountain Ventures', url: 'https://mmv.vc/' },
	{ slug: 'mendoza', name: 'Mendoza Ventures', url: 'https://mendoza-ventures.com/portfolio/' },
	{ slug: 'menlo', name: 'Menlo Ventures', url: 'https://menlovc.com/portfolio/' },
	{ slug: 'mercuri', name: 'Mercuri', url: 'https://www.mercuri.vc/portfolio' },
	{ slug: 'msc', name: 'Meridian Street Capital', url: 'https://msc.vc/#partners' },
	{ slug: 'meron', name: 'Meron Capital', url: 'https://www.meron.vc/#portfolio' },
	{ slug: 'merus', name: 'Merus Capital', url: 'https://www.meruscap.com/portfolio' },
	{ slug: 'metaplanet', name: 'Metaplanet', url: 'https://metaplanet.com/portfolio' },
	{ slug: 'metaprop', name: 'MetaProp', url: 'https://www.metaprop.com/portfolio' },
	{ slug: 'mfv', name: 'MFV Partners', url: 'https://www.mfvpartners.com/portfolio/' },
	{ slug: 'mhs', name: 'MHS Capital', url: 'http://www.mhscapital.com/portfolio/' },
	{ slug: 'mig', name: 'MIG Capital', url: 'https://www.mig.ag/en/portfolio/' },
	{ slug: 'mizmaa', name: 'Mizmaa Ventures', url: 'https://www.mizmaa.com/portfolio' },
	{ slug: 'mmc', name: 'MMC Ventures', url: 'https://mmc.vc/portfolio/' },
	{ slug: 'moderne', name: 'Moderne Ventures', url: 'https://www.moderneventures.com/portfolio' },
	{ slug: 'monashees', name: 'Monashees', url: 'https://www.monashees.com/portfolio' },
	{ slug: 'moneta', name: 'Moneta Ventures', url: 'https://www.moneta.vc/portfolio/' },
	{ slug: 'moonshots', name: 'Moonshots Capital', url: 'https://moonshotscapital.com/portfolios/' },
	{ slug: 'morpheus', name: 'Morpheus Ventures', url: 'https://morpheus.com/portfolio/' },
	{ slug: 'mosaic', name: 'Mosaic Ventures', url: 'https://www.mosaicventures.com/portfolio' },
	{ slug: 'mouro', name: 'Mouro Capital', url: 'https://www.mourocapital.com/our-portfolio/' },
	{ slug: 'moxxie', name: 'Moxxie Ventures', url: 'https://www.moxxie.vc/#Portfolio' },
	{ slug: 'mubadala', name: 'Mubadala Capital', url: 'https://www.mubadalacapital.ae/portfolio' },
	{ slug: 'mucker', name: 'Mucker Capital', url: 'https://mucker.com/our-companies/' },
	{ slug: 'munichre', name: 'Munich Re Ventures', url: 'https://www.munichre.com/mrv/en/portfolio.html' },
	{ slug: 'muse', name: 'Muse Capital', url: 'https://www.musecapital.vc/portfolio' },
	{ slug: 'musha', name: 'Musha Ventures', url: 'https://www.mushaventures.com/' },
	{ slug: 'ngpartners', name: 'National Grid Partners', url: 'https://www.ngpartners.com/portfolio' },
	{ slug: 'ndcapital', name: 'ND Capital', url: 'https://nd.capital/#portfolio' },
	{ slug: 'nea', name: 'NEA', url: 'https://www.nea.com/portfolio?category=all' },
	{ slug: 'necessary', name: 'Necessary Ventures', url: 'https://www.necessary.vc/portfolio' },
	{ slug: 'neotribe', name: 'Neotribe Ventures', url: 'https://www.neotribe.vc/portfolio' },
	{ slug: 'newmarkets', name: 'New Markets Venture Partners', url: 'https://www.newmarketsvp.com/portfolio' },
	{ slug: 'newstack', name: 'New Stack Ventures', url: 'https://www.newstack.com/#portfolio' },
	{ slug: 'newfund', name: 'Newfund Capital', url: 'https://newfundcap.com/portfolio' },
	{ slug: 'nextfrontier', name: 'Next Frontier Capital', url: 'https://nextfrontiercapital.com/portfolio' },
	{ slug: 'nextplay', name: 'Next Play Ventures', url: 'https://www.nextplayventures.com/companies' },
	{ slug: 'nextview', name: 'NextView Ventures', url: 'https://nextview.vc/investments/all/' },
	{ slug: 'nexus', name: 'Nexus Venture Partners', url: 'https://nexusvp.com/companies/' },
	{ slug: 'nfx', name: 'NFX', url: 'https://www.nfx.com/companies' },
	{ slug: 'night', name: 'Night Ventures', url: 'https://www.nightventures.com/' },
	{ slug: 'nlc', name: 'NLC Health Ventures', url: 'https://www.nlc.health/portfolio' },
	{ slug: 'node', name: 'Node.vc', url: 'https://www.node.vc/investments' },
	{ slug: 'noemis', name: 'Noemis Ventures', url: 'https://www.noemisventures.com/portfolio' },
	{ slug: 'norrsken', name: 'Norrsken VC', url: 'https://www.norrsken.vc/portfolio' },
	{ slug: 'northerngritstone', name: 'Northern Gritstone', url: 'https://www.northern-gritstone.com/portfolio' },
	{ slug: 'northpond', name: 'Northpond Ventures', url: 'https://www.npv.vc/portfolio/' },
	{ slug: 'northstar', name: 'Northstar', url: 'https://www.northstar.vc/portfolio' },
	{ slug: 'northzone', name: 'Northzone', url: 'https://northzone.com/portfolio' },
	{ slug: 'norwest', name: 'Norwest', url: 'https://www.norwest.com/companies' },
	{ slug: 'notable', name: 'Notable Capital', url: 'https://www.notablecap.com/companies' },
	{ slug: 'notation', name: 'Notation Capital', url: 'https://notation.vc/companies/' },
	{ slug: 'nphard', name: 'NP-Hard Ventures', url: 'https://nphard.vc/' },
	{ slug: 'nucleus', name: 'Nucleus Capital', url: 'https://www.nucleus-capital.com/' },
	{ slug: 'nuwa', name: 'Nuwa Capital', url: 'https://www.nuwacapital.io/portfolio' },
	{ slug: 'nxtp', name: 'NXTP Ventures', url: 'https://www.nxtp.vc/portfolio' },
	{ slug: 'nyca', name: 'Nyca Partners', url: 'https://www.nyca.com/companies' },
	{ slug: 'obvious', name: 'Obvious Ventures', url: 'https://obvious.com/portfolio/' },
	{ slug: 'oca', name: 'OCA Ventures', url: 'https://www.ocaventures.com/portfolio/' },
	{ slug: 'oceanazul', name: 'Ocean Azul Partners', url: 'https://oceanazulpartners.com/portfolio/' },
	{ slug: 'octopus', name: 'Octopus Ventures', url: 'https://octopusventures.com/portfolio/' },
	{ slug: 'offline', name: 'Offline Ventures', url: 'https://offline.vc/portfolio' },
	{ slug: 'okapi', name: 'Okapi Venture Capital', url: 'https://okapivc.com/portfolio/' },
	{ slug: 'omers', name: 'OMERS Ventures', url: 'https://www.omersventures.com/companies' },
	{ slug: 'omnivore', name: 'Omnivore', url: 'https://omnivore.vc/portfolio' },
	{ slug: 'oneway', name: 'One Way Ventures', url: 'https://www.onewayvc.com/portfolio' },
	{ slug: 'oneequity', name: 'OneEquity', url: 'https://www.oneequity.com/portfolio' },
	{ slug: 'onevc', name: 'ONEVC', url: 'https://www.onevc.vc/#portfolio' },
	{ slug: 'openocean', name: 'OpenOcean', url: 'https://www.openocean.vc/portfolio' },
	{ slug: 'operator', name: 'Operator Partners', url: 'https://www.operatorpartners.com/portfolio' },
	{ slug: 'orbimed', name: 'OrbiMed', url: 'https://www.orbimed.com/portfolio/' },
	{ slug: 'origin', name: 'Origin Ventures', url: 'https://www.originventures.com/portfolio' },
	{ slug: 'origins', name: 'Origins', url: 'https://www.origins.fund/portfolio' },
	{ slug: 'oss', name: 'OSS Capital', url: 'https://oss.capital/portfolio/' },
	{ slug: 'otb', name: 'OTB Ventures', url: 'https://otb.vc/portfolio/' },
	{ slug: 'ourcrowd', name: 'OurCrowd', url: 'https://www.ourcrowd.com/portfolio/all' },
	{ slug: 'outlander', name: 'Outlander VC', url: 'https://outlander.vc/portfolio/' },
	{ slug: 'outsiders', name: 'Outsiders Fund', url: 'https://www.outsidersfund.com/portfolio' },
	{ slug: 'overkill', name: 'Overkill Ventures', url: 'https://www.overkill.vc/portfolio' },
	{ slug: 'overlook', name: 'Overlook Ventures', url: 'https://www.overlook.vc/portfolio' },
	{ slug: 'overture', name: 'Overture', url: 'https://www.overture.vc/portfolio' },
	{ slug: 'overwater', name: 'Overwater Ventures', url: 'https://www.overwater.vc/portfolio/' },
	{ slug: 'ovni', name: 'OVNI Capital', url: 'https://www.ovni.capital/portfolio' },
	{ slug: 'owl', name: 'Owl Ventures', url: 'https://www.owlvc.com/portfolio' },
	{ slug: 'p1', name: 'P1 Ventures', url: 'https://www.p1.ventures/portfolio' },
	{ slug: 'paladin', name: 'Paladin Capital Group', url: 'https://www.paladincapgroup.com/portfolio/' },
	{ slug: 'palladium', name: 'Palladium', url: 'https://www.palladiumequity.com/investments' },
	{ slug: 'palmdrive', name: 'Palm Drive Capital', url: 'https://palmdrive.vc/portfolio/' },
	{ slug: 'panache', name: 'Panache Ventures', url: 'https://www.panache.vc/portfolio' },
	{ slug: 'pangaea', name: 'Pangaea Ventures', url: 'https://www.pangaeaventures.com/portfolio' },
	{ slug: 'pantera', name: 'Pantera Capital', url: 'https://panteracapital.com/portfolio/' },
	{ slug: 'pareto', name: 'Pareto Ventures', url: 'https://www.pareto.vc/portfolio' },
	{ slug: 'parkwalk', name: 'Parkwalk', url: 'https://parkwalk.vc/portfolio/' },
	{ slug: 'partech', name: 'Partech', url: 'https://partechpartners.com/companies' },
	{ slug: 'pathbreaker', name: 'Pathbreaker Ventures', url: 'https://www.pathbreakervc.com/companies' },
	{ slug: 'patron', name: 'Patron', url: 'https://patron.fund/portfolio' },
	{ slug: 'peakbridge', name: 'PeakBridge', url: 'https://peakbridge.vc/portfolio/' },
	{ slug: 'pear', name: 'Pear VC', url: 'https://pear.vc/companies/' },
	{ slug: 'pebblebed', name: 'Pebblebed', url: 'https://pebblebed.com/portfolio' },
	{ slug: 'picksandshovels', name: 'Picks and Shovels', url: 'https://www.picksandshovelsvc.com/#portfolio' },
	{ slug: 'picus', name: 'Picus Capital', url: 'https://www.picuscap.com/portfolio' },
	{ slug: 'pillar', name: 'Pillar VC', url: 'https://www.pillar.vc/companies/' },
	{ slug: 'pioneer', name: 'Pioneer Fund', url: 'https://www.pioneerfund.vc/portfolio' },
	{ slug: 'pitango', name: 'Pitango', url: 'https://www.pitango.com/portfolio/' },
	{ slug: 'playground', name: 'Playground Global', url: 'https://www.playground.vc/portfolio' },
	{ slug: 'plg', name: 'PLG Ventures', url: 'https://www.plgventures.com/#portfolio' },
	{ slug: 'plugandplay', name: 'Plug and Play', url: 'https://www.plugandplaytechcenter.com/innovation-services/startups/our-startups' },
	{ slug: 'plumalley', name: 'Plum Alley', url: 'https://plumalley.co/spv-portfolio' },
	{ slug: 'plural', name: 'Plural', url: 'https://www.pluralplatform.com/portfolio' },
	{ slug: 'pointnine', name: 'Point Nine', url: 'https://www.pointnine.com/companies' },
	{ slug: 'p72', name: 'Point72 Ventures', url: 'https://p72.vc/portfolio/' },
	{ slug: 'polaris', name: 'Polaris Partners', url: 'https://polarispartners.com/companies-list' },
	{ slug: 'powerhouse', name: 'Powerhouse Ventures', url: 'https://powerhouse-ventures.co/portfolio' },
	{ slug: 'precursor', name: 'Precursor Ventures', url: 'https://precursorvc.com/portfolio/' },
	{ slug: 'prelude', name: 'Prelude Ventures', url: 'https://www.preludeventures.com/portfolio' },
	{ slug: 'presence', name: 'Presence Capital', url: 'https://www.presencecap.com/#portfolio' },
	{ slug: 'primary', name: 'Primary Venture Partners', url: 'https://www.primary.vc/portfolio/by-investor' },
	{ slug: 'primeimpact', name: 'Prime Impact Fund', url: 'https://www.primeimpactfund.com/portfolio' },
	{ slug: 'primemovers', name: 'Prime Movers Lab', url: 'https://www.primemoverslab.com/portfolio/' },
	{ slug: 'primetime', name: 'Prime Time Partners', url: 'https://www.primetimepartners.com/portfolio' },
	{ slug: 'propeller', name: 'Propeller', url: 'https://propellervc.com/portfolio' },
	{ slug: 'psv', name: 'PSV', url: 'https://www.psv.xyz/portfolio' },
	{ slug: 'push', name: 'PUSH VC', url: 'https://push.vc/portfolio' },
	{ slug: 'qed', name: 'QED Investors', url: 'https://www.qedinvestors.com/companies' },
	{ slug: 'qualcomm', name: 'Qualcomm Ventures', url: 'https://www.qualcommventures.com/portfolio/' },
	{ slug: 'quantonation', name: 'Quantonation', url: 'https://www.quantonation.com/portfolio/' },
	{ slug: 'quest', name: 'Quest Venture Partners', url: 'https://www.questvp.com/portfolio.html' },
	{ slug: 'quiet', name: 'Quiet Capital', url: 'https://quiet.com/portfolio/' },
	{ slug: 'qumra', name: 'Qumra Capital', url: 'https://qumracapital.com/portfolio/' },
	{ slug: 'quona', name: 'Quona Capital', url: 'https://quona.com/portfolio/' },
	{ slug: 'r7', name: 'R7', url: 'https://www.r7.vc/' },
	{ slug: 'racap', name: 'RA Capital', url: 'https://www.racap.com/portfolio' },
	{ slug: 'race', name: 'Race Capital', url: 'https://race.capital/companies' },
	{ slug: 'radian', name: 'Radian Capital', url: 'https://www.radiancapital.com/companies' },
	{ slug: 'radical', name: 'Radical Ventures', url: 'https://radical.vc/portfolio/' },
	{ slug: 'radius', name: 'Radius Capital', url: 'https://www.radius.capital/portfolio' },
	{ slug: 'rainfall', name: 'Rainfall Ventures', url: 'https://www.rainfall.com/' },
	{ slug: 'rally', name: 'Rally Ventures', url: 'https://www.rallyventures.com/investments/' },
	{ slug: 'rarebreed', name: 'RareBreed Ventures', url: 'https://www.rarebreed.vc/companies' },
	{ slug: 'reach', name: 'Reach Capital', url: 'https://www.reachcapital.com/companies/' },
	{ slug: 'recall', name: 'Recall Capital', url: 'https://www.recall.capital/portfolio' },
	{ slug: 'recvc', name: 'Reciprocal Ventures', url: 'https://recvc.com/portfolio' },
	{ slug: 'recursive', name: 'Recursive Ventures', url: 'https://www.recursiveventures.com/' },
	{ slug: 'redbear', name: 'Red Bear Ventures', url: 'https://www.redbear.vc/portfolio' },
	{ slug: 'redsea', name: 'Red Sea Ventures', url: 'https://www.redseaventures.com/' },
	{ slug: 'redswan', name: 'Red Swan Ventures', url: 'https://www.redswanventures.com/portfolio' },
	{ slug: 'redbud', name: 'Redbud VC', url: 'https://redbud.vc/portfolio' },
	{ slug: 'redpoint', name: 'Redpoint', url: 'https://www.redpoint.com/companies/' },
	{ slug: 'refashiond', name: 'REFASHIOND Ventures', url: 'https://www.refashiond.com/fund-i-portfolio' },
	{ slug: 'relay', name: 'Relay Ventures', url: 'https://relay.vc/portfolio/' },
	{ slug: 'renegade', name: 'Renegade Partners', url: 'https://www.renegadepartners.com/companies' },
	{ slug: 'renewal', name: 'Renewal Funds', url: 'https://www.renewalfunds.com/portfolio/' },
	{ slug: 'resolute', name: 'Resolute Ventures', url: 'https://www.resolute.vc/companies' },
	{ slug: 'restive', name: 'Restive', url: 'https://www.restive.com/our-portfolio' },
	{ slug: 'ret', name: 'RET Ventures', url: 'https://www.ret.vc/portfolio' },
	{ slug: 'ribbit', name: 'Ribbit Capital', url: 'https://www.ribbitcap.com/rebels' },
	{ slug: 'riot', name: 'Riot Ventures', url: 'https://riot.vc/#portfolio' },
	{ slug: 'riverpark', name: 'RiverPark Ventures', url: 'https://riverparkvc.com/portfolio/' },
	{ slug: 'roble', name: 'Roble Ventures', url: 'https://www.robleventures.com/portfolio' },
	{
		slug: 'rockhealth',
		name: 'Rock Health Capital',
		url: 'https://rockhealthcapital.com/portfolio/'
	},
	{
		slug: 'rockies',
		name: 'Rockies Venture Fund',
		url: 'https://rockiesventurefund.com/portfolio'
	},
	{ slug: 'rogue', name: "Rogue Women's Fund", url: 'https://www.roguewmn.com/#Portfolio' },
	{ slug: 'rootvc', name: 'Root Ventures', url: 'https://root.vc/' },
	{ slug: 'rre', name: 'RRE Ventures', url: 'https://rre.com/portfolio' },
	{ slug: 'rtp', name: 'RTP Global', url: 'https://rtp.vc/our-companies/' },
	{ slug: 's2g', name: 'S2G Investments', url: 'https://www.s2ginvestments.com/companies' },
	{ slug: 's3vc', name: 'S3 Ventures', url: 'https://www.s3vc.com/companies-all' },
	{
		slug: 'saasvc',
		name: 'SaaS Ventures',
		url: 'https://saasventurecapital.com/portfolio?team=All'
	},
	{ slug: 'salesforce', name: 'Salesforce Ventures', url: 'https://salesforceventures.com/portfolio/' },
	{ slug: 'salt', name: 'Salt VC', url: 'https://salt.vc/portfolio' },
	{ slug: 'sante', name: 'Santé Ventures', url: 'https://sante.com/portfolio' },
	{ slug: 'sapphire', name: 'Sapphire Ventures', url: 'https://sapphireventures.com/companies/' },
	{ slug: 'satgana', name: 'Satgana', url: 'https://www.satgana.com/portfolio' },
	{
		slug: 'schematic',
		name: 'Schematic Ventures',
		url: 'https://www.schematicventures.com/#portfolio'
	},
	{ slug: 'scifi', name: 'SciFi VC', url: 'https://scifi.vc/#portfolio' },
	{ slug: 'scifounders', name: 'SciFounders', url: 'https://www.scifounders.com/portfolio' },
	{ slug: 'scout', name: 'Scout Ventures', url: 'https://www.scout.vc/companies' },
	{ slug: 'seedcapital', name: 'Seed Capital', url: 'https://www.seedcapital.dk/our-family' },
	{ slug: 'seedcamp', name: 'Seedcamp', url: 'https://seedcamp.com/our-companies/' },
	{ slug: 'sentiero', name: 'Sentiero Ventures', url: 'https://sentiero.vc/portfolio/' },
	{ slug: 'sequoia', name: 'Sequoia Capital', url: 'https://www.sequoiacap.com/our-companies/' },
	{ slug: 'seraphim', name: 'Seraphim Space', url: 'https://seraphim.vc/portfolio/' },
	{ slug: 'serena', name: 'Serena Ventures', url: 'https://www.serenaventures.com/portfolio' },
	{ slug: 'sevensevensix', name: 'Seven Seven Six', url: 'https://sevensevensix.com/portfolio' },
	{ slug: 'shield', name: 'Shield Capital', url: 'https://shieldcap.com/#companies' },
	{ slug: 'shima', name: 'Shima Capital', url: 'https://shima.capital/investments/' },
	{ slug: 'shine', name: 'Shine Capital', url: 'https://www.shine.vc/portfolio' },
	{ slug: 'shrug', name: 'Shrug Capital', url: 'https://www.shrug.vc/portfolio' },
	{ slug: 'sierra', name: 'Sierra Ventures', url: 'https://www.sierraventures.com/portfolio' },
	{ slug: 'sigmaprime', name: 'Sigma Prime Ventures', url: 'http://www.sigmaprime.com/portfolio' },
	{ slug: 'signalfire', name: 'SignalFire', url: 'https://www.signalfire.com/portfolio' },
	{ slug: 'silentvc', name: 'Silent Ventures', url: 'https://silentvc.com/#portfolio' },
	{ slug: 'silversmith', name: 'Silversmith', url: 'https://www.silversmith.com/portfolio' },
	{ slug: 'sixthirty', name: 'SixThirty', url: 'https://sixthirty.co/startup-portfolio/' },
	{ slug: 'sixty8', name: 'Sixty8 Capital', url: 'https://www.sixty8.capital/companies' },
	{ slug: 'slow', name: 'Slow Ventures', url: 'https://slow.co/about/' },
	{
		slug: 'socialleverage',
		name: 'Social Leverage',
		url: 'https://socialleverage.com/portfolio/'
	},
	{ slug: 'sofinnova', name: 'Sofinnova Investments', url: 'https://www.sofinnova.com/portfolio/' },
	{ slug: 'sogal', name: 'SoGal Ventures', url: 'https://www.sogalventures.com/portfolio' },
	{ slug: 'soma', name: 'Soma Capital', url: 'https://somacap.com/portfolio?tab=all' },
	{ slug: 'sosv', name: 'SOSV', url: 'https://sosv.com/portfolio/' },
	{
		slug: 'southparkcommons',
		name: 'South Park Commons',
		url: 'https://www.southparkcommons.com/companies'
	},
	{ slug: 'spacecadet', name: 'Space Cadet', url: 'https://spacecadet.ventures/portfolio' },
	{ slug: 'spark', name: 'Spark Capital', url: 'https://www.sparkcapital.com/companies' },
	{ slug: 'spice', name: 'Spice Capital', url: 'https://www.spicecapital.xyz/portfolio' },
	{
		slug: 'springtime',
		name: 'SpringTime Ventures',
		url: 'https://springtimeventures.com/portfolio/'
	},
	{ slug: 'sprout', name: 'Sprout Fund', url: 'https://sproutfund.vc/companies/' },
	{ slug: 'stageone', name: 'StageOne Ventures', url: 'https://stageonevc.com/portfolio/' },
	{
		slug: 'standardindustries',
		name: 'Standard Industries',
		url: 'https://standardindustries.com/our-businesses/standard-investments/venture-capital'
	},
	{ slug: 'startingline', name: 'Starting Line', url: 'https://www.startingline.vc/portfolio' },
	{ slug: 'story', name: 'Story Ventures', url: 'https://www.storyventures.vc/portfolio' },
	{
		slug: 'stoutstreet',
		name: 'Stout Street Capital',
		url: 'https://www.stoutstreetcapital.com/#portfolio'
	},
	{
		slug: 'straydog',
		name: 'Stray Dog Capital',
		url: 'https://straydogcapital.com/our-portfolio/'
	},
	{
		slug: 'streamlined',
		name: 'Streamlined Ventures',
		url: 'https://www.streamlined.vc/companies'
	},
	{ slug: 'stripes', name: 'Stripes', url: 'https://www.stripes.co/investments#sort=all' },
	{ slug: 'strive', name: 'STRIVE', url: 'https://strive.vc/en/portfolio' },
	{ slug: 'strongvc', name: 'Strong Ventures', url: 'https://strongvc.notion.site/' },
	{ slug: 'struck', name: 'Struck Capital', url: 'https://struckcapital.com/portfolio/' },
	{ slug: 'sugar', name: 'Sugar Capital', url: 'https://www.sugarcap.com/' },
	{ slug: 'superangel', name: 'SuperAngel', url: 'https://www.superangel.vc/#portfolio' },
	{ slug: 'superhero', name: 'Superhero', url: 'https://superherocapital.com/portfolio/' },
	{
		slug: 'supermoon',
		name: 'Supermoon Capital',
		url: 'https://supermooncapital.com/portfolio'
	},
	{ slug: 'supernode', name: 'Supernode Ventures', url: 'https://www.supernode.vc/portfolio' },
	{
		slug: 'supernova',
		name: 'Supernova Invest',
		url: 'https://supernovainvest.com/portfolio-sni/'
	},
	{ slug: 'svangel', name: 'SV Angel', url: 'https://svangel.com/portfolio' },
	{
		slug: 'systemiq',
		name: 'Systemiq Capital',
		url: 'https://www.systemiqcapital.earth/portfolio-overview'
	},
	{ slug: 'targetglobal', name: 'Target Global', url: 'https://www.targetglobal.vc/portfolio' },
	{ slug: 'tau', name: 'Tau Ventures', url: 'https://www.tauventures.com/portfolio' },
	{ slug: 'tcg', name: 'TCG', url: 'https://tcg.co/portfolio/' },
	{ slug: 'tcv', name: 'TCV', url: 'https://www.tcv.com/partnerships' },
	{ slug: 'team8', name: 'Team8', url: 'https://team8.vc/portfolio/' },
	{ slug: 'techstars', name: 'Techstars', url: 'https://www.techstars.com/portfolio' },
	{
		slug: 'telluride',
		name: 'Telluride Venture Network',
		url: 'https://tellurideventurenetwork.com/portfolio/'
	},
	{ slug: 'teneleven', name: 'Ten Eleven', url: 'https://www.1011vc.com/portfolio' },
	{ slug: 'ten13', name: 'TEN13', url: 'https://www.ten13.vc/portfolio' },
	{
		slug: 'tenoneten',
		name: 'TenOneTen Ventures',
		url: 'https://www.tenoneten.com/portfolio'
	},
	{
		slug: 'artemis',
		name: 'The Artemis Fund',
		url: 'https://www.theartemisfund.com/portfolio/'
	},
	{ slug: 'council', name: 'The Council', url: 'https://www.thecouncil.co/fund-portfolio' },
	{
		slug: 'footprint',
		name: 'The Footprint Firm',
		url: 'https://thefootprintfirm.com/investment/our-portfolio'
	},
	{ slug: 'helm', name: 'The Helm', url: 'https://thehelm.co/invest/our-portfolio/' },
	{ slug: 'thelab', name: 'The Lab Ventures', url: 'https://www.thelabventures.com/#portfolio' },
	{ slug: 'longevity', name: 'The Longevity Fund', url: 'https://longevity.vc/portfolio' },
	{ slug: 'venturecity', name: 'The Venture City', url: 'https://www.theventure.city/companies' },
	{
		slug: 'tvc',
		name: 'The Venture Collective',
		url: 'https://www.theventurecollective.com/portfolio/'
	},
	{ slug: 'thirdprime', name: 'Third Prime', url: 'https://www.thirdprime.vc/portfolio' },
	{
		slug: 'thirdrock',
		name: 'Third Rock Ventures',
		url: 'https://www.thirdrockventures.com/portfolio'
	},
	{ slug: 'thirdsphere', name: 'Third Sphere', url: 'https://thirdsphere.com/portfolio/all/' },
	{ slug: 'thomabravo', name: 'Thoma Bravo', url: 'https://www.thomabravo.com/portfolio' },
	{ slug: 'timon', name: 'Timon Capital', url: 'https://www.timoncapital.com/portfolio' },
	{ slug: 'tlv', name: 'TLV Partners', url: 'https://tlv.partners/portfolio/' },
	{ slug: 'tmv', name: 'TMV', url: 'https://www.tmv.vc/companies' },
	{ slug: 'tnbaura', name: 'TNB Aura', url: 'https://www.tnbaura.vc/portfolio' },
	{ slug: 'toba', name: 'Toba Capital', url: 'https://tobacapital.com/portfolio' },
	{ slug: 'townhall', name: 'Town Hall Ventures', url: 'https://www.townhallventures.com/portfolio' },
	{ slug: 'toyota', name: 'Toyota Ventures', url: 'https://toyota.ventures/portfolio.html' },
	{
		slug: 'trailhead',
		name: 'Trailhead Capital',
		url: 'https://www.trailheadcap.com/portfolio-companies'
	},
	{ slug: 'transformation', name: 'Transformation Capital', url: 'https://transformcap.com/partner-companies' },
	{ slug: 'transition', name: 'Transition', url: 'https://transition.vc/companies' },
	{
		slug: 'trianglepeak',
		name: 'Triangle Peak',
		url: 'https://www.trianglepeakpartners.com/technology/'
	},
	{ slug: 'triatomic', name: 'Triatomic Capital', url: 'https://www.triatomic.ai/#Portfolio' },
	{ slug: 'tribecap', name: 'Tribe Capital', url: 'https://tribecap.co/portfolio' },
	{
		slug: 'tribecavp',
		name: 'Tribeca Venture Partners',
		url: 'https://tribecavp.com/companies/'
	},
	{ slug: 'trousdale', name: 'Trousdale Ventures', url: 'https://trousdale.vc/portfolio/' },
	{ slug: 'trueventures', name: 'True Ventures', url: 'https://www.trueventures.com/portfolio' },
	{
		slug: 'truewealth',
		name: 'True Wealth Ventures',
		url: 'https://truewealthvc.com/portfolio/'
	},
	{ slug: 'tsvc', name: 'TSVC', url: 'https://www.tsvcap.com/portfolio-new' },
	{ slug: 'tusk', name: 'Tusk Venture Partners', url: 'https://www.tusk.vc/portfolio' },
	{ slug: 'twelvebelow', name: 'Twelve Below', url: 'https://www.twelvebelow.co/portfolio' },
	{ slug: 'twentytwo', name: 'Twenty Two Ventures', url: 'https://twentytwo.vc/portfolio' },
	{ slug: 'twine', name: 'Twine Ventures', url: 'https://www.twineventures.com/#portfolio' },
	{ slug: 'typeone', name: 'Type One Ventures', url: 'https://type1ventures.com/portfolio' },
	{ slug: 'ulu', name: 'Ulu Ventures', url: 'https://uluventures.com/companies/' },
	{ slug: 'uncork', name: 'Uncork Capital', url: 'https://uncorkcapital.com/companies/' },
	{ slug: 'underline', name: 'Underline Ventures', url: 'https://underline.vc/portfolio' },
	{
		slug: 'undeterred',
		name: 'Undeterred Capital',
		url: 'https://www.undeterredcapital.com/portfolio'
	},
	{
		slug: 'unicornindia',
		name: 'Unicorn India Ventures',
		url: 'https://www.unicornivc.com/deep-tech-venture-capital-portfolio'
	},
	{ slug: 'usv', name: 'Union Square Ventures', url: 'https://www.usv.com/companies/' },
	{ slug: 'uniseed', name: 'Uniseed', url: 'https://www.uniseed.com/portfolio' },
	{
		slug: 'unshackled',
		name: 'Unshackled Ventures',
		url: 'https://www.unshackledvc.com/portfolio'
	},
	{ slug: 'untapped', name: 'Untapped Capital', url: 'https://untapped.vc/' },
	{ slug: 'unusual', name: 'Unusual Ventures', url: 'https://www.unusual.vc/portfolio/' },
	{ slug: 'uppartners', name: 'UP Partners', url: 'https://up.partners/companies/' },
	{ slug: 'upfront', name: 'Upfront Ventures', url: 'https://upfront.com/portfolio' },
	{
		slug: 'uphonest',
		name: 'UpHonest Capital',
		url: 'https://www.uphonestcapital.com/portfolios'
	},
	{ slug: 'upper90', name: 'Upper90', url: 'https://upper90.io/portfolio' },
	{ slug: 'upslope', name: 'Upslope Ventures', url: 'https://www.upslope.vc/investments' },
	{ slug: 'urban', name: 'Urban Innovation Fund', url: 'https://www.urban.vc/portfolio' },
	{ slug: 'v1vc', name: 'V1.VC', url: 'https://www.v1.vc/#companies' },
	{ slug: 'valar', name: 'Valar Ventures', url: 'https://www.valar.com/' },
	{ slug: 'valia', name: 'Valia Ventures', url: 'https://www.valia.vc/portfolioindex' },
	{
		slug: 'valorcapitalgroup',
		name: 'Valor Capital Group',
		url: 'https://valorcapitalgroup.com/companies/?type=list&country=all'
	},
	{ slug: 'valorventures', name: 'Valor Ventures', url: 'https://valor.vc/portfolio' },
	{ slug: 'vamosventures', name: 'VamosVentures', url: 'https://vamosventures.com/portfolio/' },
	{ slug: 'vanedge', name: 'Vanedge Capital', url: 'https://www.vanedgecapital.com/companies/' },
	{ slug: 'variant', name: 'Variant', url: 'https://variant.fund/portfolio/' },
	{ slug: 'vastvc', name: 'Vast Ventures', url: 'https://www.vastvc.com/portfolio/' },
	{ slug: 'vendep', name: 'Vendep Capital', url: 'https://www.vendep.com/portfolio' },
	{ slug: 'venrock', name: 'Venrock', url: 'https://www.venrock.com/companies/' },
	{
		slug: 'venturefriends',
		name: 'VentureFriends',
		url: 'https://www.venturefriends.vc/portfolio'
	},
	{
		slug: 'venturesplatform',
		name: 'Ventures Platform',
		url: 'https://www.venturesplatform.com/portfolio'
	},
	{ slug: 'venturesouq', name: 'VentureSouq', url: 'https://www.venturesouq.com/portfolio' },
	{
		slug: 'vertex',
		name: 'Vertex Ventures Israel',
		url: 'https://www.vertexventures.co.il/#portfolio'
	},
	{ slug: 'vestigo', name: 'Vestigo Ventures', url: 'https://www.vestigoventures.com/' },
	{ slug: 'vibevc', name: 'Vibe Capital', url: 'https://vibe.vc/companies' },
	{ slug: 'viking', name: 'Viking', url: 'https://vikingglobal.com/private-equity-portfolio/' },
	{ slug: 'villageglobal', name: 'Village Global', url: 'https://www.villageglobal.com/portfolio' },
	{ slug: 'vineventures', name: 'Vine Ventures', url: 'https://vineventures.com/' },
	{ slug: 'viola', name: 'Viola', url: 'https://www.viola-group.com/portfolio/' },
	{ slug: 'vireo', name: 'Vireo Ventures', url: 'https://vireo.vc/portfolio' },
	{ slug: 'virtuevc', name: 'Virtue', url: 'https://www.virtuevc.com/portfolio' },
	{ slug: 'visiblehands', name: 'Visible Hands', url: 'https://www.visiblehands.vc/portfolio' },
	{
		slug: 'visibleventures',
		name: 'Visible Ventures',
		url: 'https://visibleventures.com/portfolio/'
	},
	{ slug: 'voimaventures', name: 'Voima Ventures', url: 'https://voimaventures.com/portfolio/' },
	{ slug: 'voloearth', name: 'VoLo Earth', url: 'https://www.voloearth.com/portfolio' },
	{ slug: 'voyagervc', name: 'Voyager Ventures', url: 'https://www.voyagervc.com/portfolio' },
	{ slug: 'vtfcapital', name: 'VTF Capital', url: 'https://vtfcapital.com/portfolio/' },
	{
		slug: 'vuventurepartners',
		name: 'VU Venture Partners',
		url: 'https://www.vuventurepartners.com/investments'
	},
	{
		slug: 'watertower',
		name: 'Watertower Ventures',
		url: 'https://www.watertowerventures.com/companies'
	},
	{ slug: 'wavemaker360', name: 'Wavemaker 360', url: 'https://www.wavemaker360.com/portfolio' },
	{ slug: 'waverley', name: 'Waverley Capital', url: 'https://www.waverleycapital.com/companies' },
	{
		slug: 'wellington',
		name: 'Wellington',
		url: 'https://www.wellington.com/en/capabilities/private-investing/our-investments'
	},
	{
		slug: 'willowgrowth',
		name: 'Willow Growth Partners',
		url: 'https://willowgrowth.com/brands/'
	},
	{
		slug: 'windham',
		name: 'Windham Capital Partners',
		url: 'https://www.windhamcap.com/portfolio'
	},
	{ slug: 'wing', name: 'Wing Venture Capital', url: 'https://www.wing.vc/companies' },
	{ slug: 'wireframe', name: 'Wireframe Ventures', url: 'https://www.wireframevc.com/portfolio' },
	{ slug: 'wischoff', name: 'Wischoff Ventures', url: 'https://www.wischoff.com/' },
	{ slug: 'wndr', name: 'WNDR', url: 'https://www.wndr.vc/portfolio' },
	{ slug: 'wondervc', name: 'Wonder Ventures', url: 'https://wondervc.com/portfolio/' },
	{ slug: 'workbench', name: 'Work-bench', url: 'https://www.work-bench.com/portfolio' },
	{
		slug: 'worklife',
		name: 'Worklife Ventures',
		url: 'https://www.worklife.vc/companies'
	},
	{ slug: 'worldfund', name: 'World Fund', url: 'https://www.worldfund.vc/portfolio' },
	{
		slug: 'wvvcapital',
		name: 'WVV Capital',
		url: 'https://www.wvvcapital.com/portfolio-companies'
	},
	{ slug: 'wxrfund', name: 'WXR Fund', url: 'https://www.wxrfund.com/portfolio' },
	{ slug: 'xange', name: 'XAnge', url: 'https://www.xange.vc/portfolio' },
	{
		slug: 'xfactorventures',
		name: 'XFactor Ventures',
		url: 'https://www.xfactor.ventures/portfolio'
	},
	{ slug: 'xfund', name: 'Xfund', url: 'https://www.xfund.com/portfolio' },
	{
		slug: 'xrcventures',
		name: 'XRC Ventures',
		url: 'https://www.xrcventures.com/portfolio'
	},
	{ slug: 'xyz', name: 'XYZ', url: 'https://www.xyz.vc/portfolio' },
	{ slug: 'ycombinator', name: 'Y Combinator', url: 'https://www.ycombinator.com/companies' },
	{ slug: 'yesvc', name: 'Yes VC', url: 'https://yes.vc/portfolio/' },
	{ slug: 'ylventures', name: 'YL Ventures', url: 'https://www.ylventures.com/portfolio/' },
	{ slug: 'zcg', name: 'ZCG', url: 'https://www.zcg.com/portfolio' },
	{
		slug: 'zeal',
		name: 'Zeal Capital Partners',
		url: 'https://www.zealcapitalpartners.com/portfolio/'
	},
	{ slug: 'zenda', name: 'Zenda', url: 'https://www.zenda.vc/portfolio/' },
	{ slug: 'zetta', name: 'Zetta Venture Partners', url: 'https://www.zettavp.com/companies' },
	{ slug: 'zigg', name: 'Zigg Capital', url: 'https://ziggcap.com/#portfolio' }
];

export const fundName = new Map(FUNDS.map((f) => [f.slug, f.name]));
export const fundBySlug = new Map(FUNDS.map((f) => [f.slug, f]));
